//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinFu.Persist.Metadata.Implementation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinFu.Persist.Metadata.Implementation.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	KCU1.TABLE_SCHEMA AS &apos;FK_TABLE_SCHEMA&apos;,	
        ///	KCU1.TABLE_NAME AS &apos;FK_TABLE_NAME&apos;,
        ///	KCU1.COLUMN_NAME AS &apos;FK_COLUMN_NAME&apos;,
        ///	KCU1.ORDINAL_POSITION AS &apos;FK_ORDINAL_POSITION&apos;,
        ///	KCU2.TABLE_SCHEMA AS &apos;UQ_TABLE_SCHEMA&apos;,	
        ///	KCU2.TABLE_NAME AS &apos;UQ_TABLE_NAME&apos;,	
        ///	KCU2.COLUMN_NAME AS &apos;UQ_COLUMN_NAME&apos;,
        ///	KCU2.ORDINAL_POSITION AS &apos;UQ_ORDINAL_POSITION&apos;,		
        ///	KCU2.CONSTRAINT_NAME AS &apos;UQ_CONSTRAINT_NAME&apos; , 
        ///	KCU1.CONSTRAINT_NAME AS &apos;FK_CONSTRAINT_NAME&apos;
        ///FROM 
        ///	INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS RC
        ///INNER  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ForeignKeys {
            get {
                return ResourceManager.GetString("ForeignKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///tc.TABLE_SCHEMA,
        ///tc.TABLE_NAME,
        ///kcu.COLUMN_NAME,
        ///kcu.ORDINAL_POSITION
        ///FROM 
        ///INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc 
        ///INNER JOIN 
        ///INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu
        ///ON 
        ///tc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME AND 
        ///tc.CONSTRAINT_TYPE = &apos;PRIMARY KEY&apos;
        ///ORDER BY 
        ///	tc.TABLE_NAME,
        ///	kcu.COLUMN_NAME,
        ///	kcu.ORDINAL_POSITION.
        /// </summary>
        internal static string PrimaryKeys {
            get {
                return ResourceManager.GetString("PrimaryKeys", resourceCulture);
            }
        }
    }
}
